# Generated by Django 4.1 on 2022-08-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('mob_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=150)),
                ('department', models.TextField(max_length=100)),
                ('course', models.TextField(max_length=100)),
                ('purpose', models.CharField(max_length=50)),
                ('materials', models.TextField(max_length=100)),
            ],
        ),
    ]
